language: objective-c
xcode_workspace: Oak.xcworkspace
xcode_scheme: Oak
env:
  global:
  - APP_NAME="Oak"
  - 'DEVELOPER_NAME="iPhone Distribution: Tomohiro Matsumura"'
  - PROFILE_NAME="OakAdHoc"
  - secure: Mxs9mmazVmzKe7+Jm5og8nZR5hqyq1yFeOUV7cYXDbEgPeBxPRTAMpLwSyAyuQPFCopwWJOzd8Q3tdXMto72eNFmzQSOKfxeW3sHM+M6MMRfEwXxsy5/S34r34rumEDDxkic1ylMFebvn3EbdXTeU5X61wtUl7G/bLqRtAM4gR1cRm2xvZsRpmlGv/KF0X6zohbk9CP5UaGgL8sQQ1SofNwezA/mfyJaQpldGMDMoNVzNwdurqcQHMQSNd9NpO7shOBf51DcauREgTK4K6G6V7MTuWf73A19n/2CJnxXtxgVU5JzCVB8vtWDkNLqbLLIll6WRVM7bVnHGoW6jTpe+9MV+yTnRN1omM3iUSOjn4x8y2iN4NBsHXObJMjV3kLX4T9PPFi2o7kE5e/HW4uIryXVDMnbnIKlH7XPQB2zWwQ/XOiwScJgqa6OuzlXwCM9p8s8zzffy5s92MWPbWFT0K2h5Y18KyRKsfQjPR7fLPVolTmZIlIuX8C4LUU8L+v+yVlI9V2QyBVMj/NO5aDnXWcaUtLp4b080Px74tAGgVO7XdFy7tGLLVmpmjw8qGKVg5wCel9Um7rSKzJROpzU26hPpppJ1Y6lgZpgqA109dpimMwD/Pbob5QkBR3cOFgqY71rMriL3jR8yTsZ6NHty3muqGplZWWuRve0CfaBwXU=
  - secure: E/I3z4Ku6azSDWj65oaYr3FSduZDoGQyeRnEUPqwykK7Dtb2o3FZB8UjW7PnZ7jx2PnSafdbgS5QP2V4IBkiCgKizjTxiQeBqMnvXgXUM5bU+Rp/1Fi3EOzXY2Dwrz8wJ0wiATx8NdL6rhaXbzfcoZHCGt4Jj27nVE+1wswc+Dn1DxB1Z67fepdXaRTYMNV3E9ZqGiIZPlx6LnY8BHWrlFW8geyF1t+p9zQFVLt8bTP6EfnT/luXkq0GGTFsP3ZxEKAWsdlM0EsHgVNNu10soe1/58H2Ym0ZGBxMcyHmOPoxZTls/aqJ8gM5blhf580eDb/6JuA6Doq8puTbzVM0KZDZ/5tiBMhMV+zpOvPfIBCnSDgXFsvnySdnfY8IWotEDOlbI087hx/AqQbHzequ6/LuDhhwT8zl5t9JqwRFCSiuvezIsTcjQpWBO4nas8VhTQewZphZOL91t+VEFIIukPuz3G3ruEAA6b0IJL2IqNZNVWIS/vMPJtNXsScVZFL1N/CE58N5+cZdrHyxmx3OfZmztMS8SsGFy/I0KOVQfDuJCSl1KeX78FbPFEYBZF0G0gf5/o8udbPD4ynSvUNizTBUiNazahfV1tVQ41eh8YEZuMJgUhPEEdVy507YmxYuGMeuKjztg4GmHcfBi6Qw8IGxvQcpsDNOT6y4RH+uv54=
before_script:
- "./Travis/Scripts/setup_gems.sh"
- "./Travis/Scripts/setup_keychain.sh"
- "./Travis/Scripts/create_secrets.sh"
script:
- "./Travis/Scripts/build_ipa.sh"
after_success:
- "./Travis/Scripts/upload_ipa.sh"
after_script:
- "./Travis/Scripts/teardown_keychain.sh"
notifications:
  slack:
    secure: WP3xYc1ZRlmu5h4LvTfVkY2tGJ2mgqjvHY6BdpFkjI1vS6VdGvDp/HHMmDEx8nLn+a68hn7cTRSrcTxV8iOsYdXQAyVw4AkRfWD3uwF5U/40etA30tHJZX8zgWA2/sM2tqb0/U2X3zbrqNYz/u4HCE6cu/r/f06D1XWT1KzcPOBfHzLeJX0uuB0WYtUTvAc2PVlQWViGuM51lQtujMeRbgrv4ccUqiZkNguZvvjKVLH74SR5nLuVGqNJkd9qQ1oH91ebxbtb8bVdO34r7EYMdLBE6KqdHWk1hgyuBWvXYNGw4aHg5GSRidZaR63OoQv+Vud/JiOiio0qAikzZNeMgIAppJ/bDkIzDT73/GfjQupCctjP0OjTj9eNj2q5o+i1CBWMmdwfCac1+aIfDz9jyJI7TlcFfoWxpVTtmFWTagPlFsKy87wQ0iBiUCXtut84ULV4Qw4qmlZUbLXtIG+WyIE2QQ1A935gnwJIu4hzCb7d445gl7T9nU9J6p0tV8tcjNQsRaYYtHhHJTafQqF0elQzl6eVgOsFPsZRDtYB/KMfhVgMF2cQSG38DTCbh05Rts3f+nXT9Z6fs9ctcR5v1e6mqKvIUIgT9aVDxWrwKBoerMeytWizNSXJE26W8bJZ8qCJ0PjTcX0u3oQEBbRlAM5iwOTxsqocxp5GEfYuTuw=
